import { StyleSheet } from "react-native";
import { white } from "react-native-paper/lib/typescript/styles/colors";

export default StyleSheet.create({
  container: {
    width: "100%",
    height: "100%",
    backgroundColor: "#FFFFFF",
    borderTopRightRadius: 40,
    borderTopLeftRadius: 40,
  },
  s: {
    marginTop: 40
  },
  labelInicio: {
    fontSize: 22,
    //fontFamily: "Dosis",
    fontWeight: "500",
    lineHeight: 28,
    letterSpacing: 0.0015,
    textAlign: "center",
    color: "#003031",
    marginTop: 24,
    marginBottom: 32,
  },
  labelAccount: {
    fontSize: 16,
    fontWeight: "normal",
    lineHeight: 19,
    letterSpacing: 0.005,
    textAlign: "center",
    color: "#003031",
  },
  labelForgetPassword: {
    fontSize: 16,
    lineHeight: 19,
    letterSpacing: 0.005,
    textDecorationLine: "underline",
    marginBottom: 32,
  },
  labelIngresa: {
    textAlign: "center",
    color: "#003031",
    fontSize: 16,
    fontWeight: "normal",
    lineHeight: 19,
    letterSpacing: 0.005,
    marginLeft: 8,
    marginBottom: 16,
  },
  labelLogin: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "bold",
    lineHeight: 18,
    letterSpacing: 0.00125,
    textAlign: "center",
    paddingVertical: 12,
  },
  labelSocial: {
    fontSize: 15,
    fontWeight: "bold",
    lineHeight: 18,
    letterSpacing: 0.00125,
    textAlign: "center",
    paddingVertical: 12,
    paddingLeft: 5,
  },
  containerForm: {
    marginRight: 15,
    marginLeft: 17,
  },
  inputTextBox: {
    height: 56,
    borderColor: "#A1AAB2",
    //fontFamily: "Roboto",
    borderRadius: 3.5,
    paddingLeft: 15,
    borderWidth: 1,
    marginBottom: 29,
  },
  inputTextBoxError: {
    height: 56,
    borderColor: "#DD3338",
    borderRadius: 3.5,
    paddingLeft: 15,
    borderWidth: 1,
  },
  labelError: {
    color: "#DD3338",
    fontSize: 12,
    lineHeight: 14,
    letterSpacing: 0.004,
    marginTop: 5,
    marginBottom: 20,
    paddingLeft: 15,
  },
  btnIniciar: {
    backgroundColor: "#132A3E",
    height: 42,
    borderRadius: 25,
    marginBottom: 24,
  },
  btnSocialAccountGoogle: {
    flexDirection: "row",
    alignItems: "center",
    borderColor: "#A1AAB2",
    paddingHorizontal: 50,
    borderWidth: 1,
    height: 42,
    width: 170,
    borderRadius: 25,
  },
  btnSocialAccountFacebook: {
    flexDirection: "row",
    alignItems: "center",
    borderColor: "#A1AAB2",
    paddingHorizontal: 45,
    borderWidth: 1,
    height: 42,
    width: 170,
    borderRadius: 25,
    marginLeft: 16,
  },
  noCuenta: {
    flexDirection: "row",
    alignSelf: "center",
    alignItems: "flex-end",
    marginBottom: 32,
  },
  containerSocial: {
    flexDirection: "row",
    alignSelf: "center",
    alignItems: "flex-end",
    marginBottom: 32,
  },
  labelRegistrate: {
    color: "#902857",
    fontSize: 16,
    fontWeight: "bold",
    lineHeight: 19,
    letterSpacing: 0.005,
    marginLeft: 8,
  },
});
